name: Scheduled Dependency Updates Template

description: >
  Reusable workflow for scheduled dependency updates. Expects SCHEDULED_UPDATES_TOKEN to be available via secrets.

on:
  workflow_call:
    inputs:
      update_command:
        required: true
        type: string
      python_version_file:
        required: false
        type: string
        default: "pyproject.toml"
        description: "File containing the Python version to use. Leave empty to disable."
      cache:
        required: false
        type: string
        default: "pip"
        description: "Package manager for caching (pip, pipenv, poetry). Leave empty to disable caching."

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ inputs.python_version_file != '' && inputs.python_version_file || null }}
          cache: ${{ inputs.cache != '' && inputs.cache || null }}

      - name: Run auto dependency update
        uses: romoh/dependencies-autoupdate@v1.1
        with:
          token: ${{ secrets.SCHEDULED_UPDATES_TOKEN }}
          update-command: ${{ inputs.update_command }}
